# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bookshelf' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bookshelf
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'PinLayout'
  pod 'Alamofire'
  pod 'XServiceLocator'
  pod 'AlamofireImage'

  target 'BookshelfTests' do
    use_frameworks!
    
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'RxCocoa'

  end

end
